config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from config import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('baton/', include('baton.urls')),
                  path('', include('ecommerce.urls')),
                  path('user/', include('user.urls')),
                  path('social-auth/',
                       include('social_django.urls', namespace='social')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/urls.py
from django.contrib import admin
from django.urls import path
from ecommerce import views

app_name = 'ecommerce'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:pk>/', views.product_detail, name='product_detail'),
    path("comment/<int:pk>/", views.comment_view, name="comment_view"),
    path('customers/', views.customer_list, name='customer_list'),
    path('customer-detail/<int:pk>/', views.customer_details, name='customer_details'),
    path('add_customer/', views.add_customer, name='add_customer'),
    path('edit_customer/<int:pk>/', views.edit_customer, name='edit_customer'),
    path('delete_customer/<int:pk>/', views.delete_customer, name='delete_customer'),
    path("toggle-favourite/<int:product_id>/", views.toggle_favourite, name="toggle_favourite"),
    path('shopping-cart/', views.view_cart, name='shopping_cart'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('remove-to-cart/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('order/', views.order_list, name='order_list'),
    path('export-data/', views.export_data, name='export_data'),
]

user/urls.py
from django.urls import path
from user import views

app_name = 'user'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_page, name="login_page"),
    path('logout/', views.logout_page, name='logout_page'),
    path('verify/', views.verify_email, name='verify'),
]

ecommerce/forms.py
from django import forms
from phonenumber_field.modelfields import PhoneNumberField
from ecommerce.models import *


class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['full_name', 'email', 'body', 'rating']

class CustomerModelForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['full_name', 'email','description','vat_number', 'address', 'phone_number']

ecommerce/views.py
import csv

from django.db.models import Avg
from django.db.models.fields import json
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View
from django.urls import reverse_lazy
from django.core.paginator import Paginator
from django.http import JsonResponse, HttpResponse
from ecommerce.utils import generate_invoice_prefix



from ecommerce.models import Product, Customer, ShoppingCart, Comment
from ecommerce.forms import CustomerModelForm

def index(request):
    search_query = request.GET.get('q', '')
    filter_type = request.GET.get('filter', '')
    products = Product.objects.all()

    if filter_type == 'date':
        products = products.order_by('-created_at')
    elif filter_type == 'name':
        products = products.order_by('name')
    elif filter_type == 'stock':
        products = products.order_by('-stock')
    elif filter_type == 'price_rating':
        products = products.order_by('-price', '-rating')

    if search_query:
        products = products.filter(name__icontains=search_query)

    # Har bir mahsulot uchun o'rtacha reyting qo'shish
    for product in products:
        product.average_rating = Comment.objects.filter(product=product).aggregate(Avg('rating'))['rating__avg'] or 0

    paginator = Paginator(products, 4)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {
        'page_obj': page_obj,
        'products': products,
    }
    return render(request, 'ecommerce/product-list.html', context)

def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    comments = Comment.objects.filter(product=product)

    # O'rtacha reytingni hisoblash
    average_rating = comments.aggregate(Avg('rating'))['rating__avg'] or 0
    product.average_rating = round(average_rating, 1)

    context = {
        'product': product,
        'comments': comments,
        'average_rating': product.average_rating,
    }
    return render(request, 'ecommerce/product-details.html', context=context)

def comment_view(request, pk):
    product = get_object_or_404(Product, id=pk)
    form  = CustomerModelForm()
    if request.method == "POST":
        form = CustomerModelForm(request.POST)

        if form.is_valid():
            comment = form.save(commit=False)
            comment.product = product
            comment.save()
            return redirect('ecommerce:product-details', pk)

        else:
            print(form.errors)

    context = {
        'form': form,
        'product': product,
    }


    return render(request, "ecommerce/product-details.html", context=context)

def customer_list(request):
    filter_type = request.GET.get('filter', '')
    search_query = request.GET.get('q', '')
    customers = Customer.objects.all()

    if filter_type == 'filter':
        customers = Customer.objects.all().order_by('full_name')
    else:
        customers = Customer.objects.all().order_by('-created_at')

    for customer in customers:
        customer.created_date = customer.created_at.strftime("%B %d, %Y")

    if search_query:
        customers = Customer.objects.filter(full_name__icontains=search_query)

    context = {
        'customers': customers,
    }

    return render(request, template_name='ecommerce/customers.html', context=context)

def customer_details(request, pk):
    customer = get_object_or_404(Customer, id=pk)
    created_date = customer.created_at.strftime("%b %d, %I:%M %p")

    context = {
        'customer': customer,
        'created_date': created_date,
    }

    return render(request, template_name='ecommerce/customer-details.html', context=context)

def add_customer(request):
    if request.method == "POST":
        form = CustomerModelForm(request.POST)
        if form.is_valid():
            customer = form.save(commit=False)
            customer.invoice_prefix = generate_invoice_prefix()
            customer.invoice_number = 1
            customer.save()
            return redirect('ecommerce:customer_list')
    else:
        form = CustomerModelForm()

    return render(request, 'ecommerce/add_customer.html', {'form': form})

def edit_customer(request, pk):
    customer = get_object_or_404(Customer, id=pk)

    if request.method == "POST":
        form = CustomerModelForm(request.POST, instance=customer)
        if form.is_valid():
            customer = form.save(commit=False)
            customer.save()
            return redirect('ecommerce:customer_list')
    else:
        form = CustomerModelForm(instance=customer)

    return render(request, 'ecommerce/edit_customer.html', {'form': form})



def delete_customer(request, pk):
    try:
        customer = Customer.objects.get(id=pk)
        customer.delete()
        return redirect('ecommerce: customer_list')
    except Customer.DoesNotExist as e:
        print(e)




def toggle_favourite(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    product.favorite = not product.favorite
    product.save()

    return JsonResponse({"favorite": product.favorite})




def view_cart(request):
    if request.user.is_authenticated:
        customer = get_object_or_404(Customer, email=request.user.email)
        cart_items = ShoppingCart.objects.filter(user=customer)

        total_price = sum(cart.get_total_price() for cart in cart_items)

        if not cart_items:
            cart_items = None
            total_price = 0

    else:
        cart_items = None
        total_price = 0

    context = {
        'cart_items': cart_items,
        'total_price': total_price
    }

    return render(request, 'ecommerce/shopping-cart.html', context)

def add_to_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        customer, created = Customer.objects.get_or_create(email=request.user.email,
                                                           defaults={'full_name': request.user.get_full_name()})

        if ShoppingCart.objects.filter(user=customer, product=product).exists():
            messages.warning(request, "Bu mahsulot allaqachon savatchaga qo‘shilgan!")
        else:
            ShoppingCart.objects.create(user=customer, product=product)
            messages.success(request, "Mahsulot savatchaga qo‘shildi!")

    return redirect('ecommerce:index')

def remove_from_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if request.user.is_authenticated:
        customer, created = Customer.objects.get_or_create(email=request.user.email,
                                                           defaults={'full_name': request.user.get_full_name()})

        cart_item = ShoppingCart.objects.filter(user=customer, product=product).first()

        if cart_item:
            cart_item.delete()
            messages.success(request, "Mahsulot savatchadan o‘chirildi!")
        else:
            messages.warning(request, "Bu mahsulot savatchada topilmadi!")
    else:
        messages.warning(request, "Iltimos, avval tizimga kiring.")

    return redirect('ecommerce:shopping_cart')


def order_list(request):
    return render(request, 'ecommerce/order-list.html')

def export_data(request):
    format = request.GET.get('format', '')
    response = None
    if format == 'csv':
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename=customer_list.csv'
        writer = csv.writer(response)
        writer.writerow(['Id', 'Full Name', 'Email', 'Phone Number', 'Address'])
        for customer in Customer.objects.all():
            writer.writerow([customer.id, customer.full_name, customer.email, customer.phone_number, customer.address])
    elif format == 'json':
        response = HttpResponse(content_type='application/json')
        data = list(Customer.objects.all().values('full_name', 'email', 'address', 'phone_number'))
        for customer in data:
            customer['phone_number'] = str(customer['phone_number'])
        response.write(json.dumps(data, indent=3))
        response['Content-Disposition'] = 'attachment; filename=customers.json'
    elif format == 'xlsx':
        pass
    else:
        response = HttpResponse(status=404)
        response.content = 'Bad request'

    return response

ecommerce/templates/ecommerce/add_customer.html
{% extends 'ecommerce/base/base.html' %}

{% block add_customer_content %}
<div class="container mt-5">
    <h2>Add Customer</h2>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <!-- Full Name Field -->
        <div class="mb-3">
            <label for="full_name" class="form-label">Full Name</label>
            <input type="text" class="form-control" id="full_name" name="full_name">
        </div>

        <!-- Email Field -->
        <div class="mb-3">
            <label for="email" class="form-label">Email</label>
            <input type="email" class="form-control" id="email" name="email">
        </div>

        <!-- Description Field -->
        <div class="mb-3">
            <label for="description" class="form-label">Description</label>
            <textarea class="form-control" id="description" name="description">{{ form.description.value }}</textarea>
        </div>

        <!-- VAT Number Field -->
        <div class="mb-3">
            <label for="vat_number" class="form-label">VAT Number</label>
            <input type="text" class="form-control" id="vat_number" name="vat_number" value="{{ form.vat_number.value }}">
        </div>

        <!-- Address Field -->
        <div class="mb-3">
            <label for="address" class="form-label">Address</label>
            <textarea class="form-control" id="address" name="address"></textarea>
        </div>

        <!-- Phone Number Field -->
        <div class="mb-3">
            <label for="phone_number" class="form-label">Phone Number</label>
            <input type="text" class="form-control" id="phone_number" name="phone_number">
        </div>

        <!-- Customer Image Field -->
        <div class="mb-3">
            <label for="customer_image" class="form-label">Customer Image</label>
            <input type="file" class="form-control" id="customer_image" name="customer_image">
        </div>

        <!-- Submit Button -->
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

ecommerce/templates/ecommerce/customer-details.html
{% extends 'ecommerce/base/base.html' %}
{% load static %}

{% block customer_detail_content %}

    <div class="card mb-3">
        <div class="card-header">
            <div class="row">
                <div class="col">
                    <div class="col">
                        <h5 class="mb-2">{{ customer.full_name }}</h5>
                        <a href="mailto:{{ customer.email }}">( {{ customer.email }})</a>
                            <button class="btn btn-falcon-default btn-sm dropdown-toggle ms-2 dropdown-caret-none"
                                type="button" data-bs-toggle="dropdown" aria-haspopup="true"
                                aria-expanded="false"><span
                                class="fas fa-ellipsis-h"></span></button>

                        <div class="dropdown-menu"><a class="dropdown-item"
                                                      href="{% url 'ecommerce:edit_customer' customer.id %}">Edit</a>
                            <div class="dropdown-divider"></div>
                            <form method="POST" action="{% url 'ecommerce:delete_customer' customer.id %}"
                                  onsubmit="return confirmDelete()">
                                {% csrf_token %}
                                <button type="submit" class="dropdown-item text-danger">Delete user</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <script>
                function confirmDelete() {
                    return confirm("Siz haqiqatdan ham ushbu foydalanuvchini o‘chirib tashlamoqchimisiz?");
                }
            </script>
            <div class="col-auto d-none d-sm-block">
                <h6 class="text-uppercase text-600"><a
                        href="{% url 'ecommerce:customer_details' customer.id %}">Customer<span
                        class="fas fa-user ms-2"></span></a></h6>
            </div>
        </div>
    </div>
    <div class="card-body border-top">
        <div class="d-flex"><span class="fas fa-user text-success me-2" data-fa-transform="down-5"></span>
            <div class="flex-1">
                <p class="mb-0">Customer was created</p>
                <p class="fs--1 mb-0 text-600">{{ created_date }}</p>
            </div>
        </div>
    </div>
    <div class="card mb-3">
        <div class="card-header">
            <div class="row align-items-center">
                <div class="col">
                    <h5 class="mb-0"><a href="{% url 'ecommerce:customer_details' customer.id %}">Details</a></h5>
                </div>
                <div class="col-auto"><a class="btn btn-falcon-default btn-sm"
                                         href="{% url 'ecommerce:edit_customer' customer.id %}"><span
                        class="fas fa-pencil-alt fs--2 me-1"></span>Update details</a></div>
            </div>
        </div>
        <div class="card-body bg-light border-top">
            <div class="row">
                <div class="col-lg col-xxl-5">
                    <h6 class="fw-semi-bold ls mb-3 text-uppercase">Account Information</h6>
                    <div class="row">
                        <div class="col-5 col-sm-4">
                            <p class="fw-semi-bold mb-1">ID</p>
                        </div>
                        <div class="col">{{ customer.id }}</div>
                    </div>
                    <div class="row">
                        <div class="col-5 col-sm-4">
                            <p class="fw-semi-bold mb-1">Created</p>
                        </div>
                        <div class="col">{{ customer.created_at|date:"Y/m/d H:i" }}</div>
                    </div>
                    <div class="row">
                        <div class="col-5 col-sm-4">
                            <p class="fw-semi-bold mb-1">Email</p>
                        </div>
                        <div class="col"><a href="mailto:{{ customer.email }}">{{ customer.email }}</a></div>
                    </div>
                    <div class="row">
                        <div class="col-5 col-sm-4">
                            <p class="fw-semi-bold mb-1">Description</p>
                        </div>
                        <div class="col">
                            <p class="fst-italic text-400 mb-1">{{ customer.description }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-5 col-sm-4">
                            <p class="fw-semi-bold mb-0">VAT number</p>
                        </div>
                        <div class="col">
                            <p class="fst-italic text-400 mb-0">{{ customer.vat_number }}</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg col-xxl-5 mt-4 mt-lg-0 offset-xxl-1">
                    <h6 class="fw-semi-bold ls mb-3 text-uppercase">Billing Information</h6>
                    <div class="row">
                        <div class="col-5 col-sm-4">
                            <p class="fw-semi-bold mb-1">Send email to</p>
                        </div>
                        <div class="col"><a href="mailto:{{ customer.email }}">{{ customer.email }}</a></div>
                    </div>
                    <div class="row">
                        <div class="col-5 col-sm-4">
                            <p class="fw-semi-bold mb-1">Address</p>
                        </div>
                        <div class="col">
                            <p class="mb-1">{{ customer.address }}</p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-5 col-sm-4">
                            <p class="fw-semi-bold mb-1">Phone number</p>
                        </div>
                        <div class="col"><a href="tel:{{ customer.phone_number }}">{{ customer.phone_number }}</a></div>
                    </div>
                    <div class="row">
                        <div class="col-5 col-sm-4">
                            <p class="fw-semi-bold mb-0">Invoice prefix</p>
                        </div>
                        <div class="col">
                            <p class="fw-semi-bold mb-0">{{ customer.generate_invoice_id }}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer border-top text-end"><a class="btn btn-falcon-default btn-sm" href="#!"><span
                class="fas fa-dollar-sign fs--2 me-1"></span>Refund</a></div>
    </div>

{% endblock %}

ecommerce/templates/ecommerce/customers.html
{% extends 'ecommerce/base/base.html' %}
{% load static %}

{% block customer_list_content %}

    <div class="card mb-3" id="customersTable"
         data-list='{"valueNames":["name","email","phone","address","joined"],"page":10,"pagination":true}'>
        <div class="card-header">
            <div class="row flex-between-center">
                <div class="col-4 col-sm-auto d-flex align-items-center pe-0">
                    <h5 class="fs-0 mb-0 text-nowrap py-2 py-xl-0">Customers</h5>
                </div>
                <div class="col-8 col-sm-auto text-end ps-2">
                    <div class="d-none" id="table-customers-actions">
                        <div class="d-flex">
                            <select class="form-select form-select-sm" aria-label="Bulk actions">
                                <option selected="">Bulk actions</option>
                                <option value="Refund">Refund</option>
                                <option value="Delete">Delete</option>
                                <option value="Archive">Archive</option>
                            </select>
                            <button class="btn btn-falcon-default btn-sm ms-2" type="button">Apply</button>
                        </div>
                    </div>
                    <div id="table-customers-replace-element">
                        <!-- Bu tugma 'add_customer' sahifasiga yo'naltiradi -->
                        <a href="{% url 'ecommerce:add_customer' %}" class="btn btn-falcon-default btn-sm">
                            <span class="fas fa-plus" data-fa-transform="shrink-3 down-2"></span>
                            <span class="d-none d-sm-inline-block ms-1">New</span>
                        </a>
                        <button class="btn btn-falcon-default btn-sm mx-2" type="button"
                                onclick="location.href='?filter=filter'">
                            <span class="fas fa-filter" data-fa-transform="shrink-3 down-2"></span>
                            <span class="d-none d-sm-inline-block ms-1">Filter</span>
                        </button>
                        <form action="{% url 'ecommerce:export_data' %}">

                            <select class="form-select" aria-label="Default select example" name="format">
                                <option value="none" selected>...</option>
                                <option value="json">Json</option>
                                <option value="xlsx">XLSX</option>
                                <option value="csv">CSV</option>
                            </select>
                            <button class="btn btn-falcon-default btn-sm" type="submit"><span
                                    class="fas fa-external-link-alt"
                                    data-fa-transform="shrink-3 down-2"></span><span
                                    class="d-none d-sm-inline-block ms-1">Export</span>
                            </button>

                        </form>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-body p-0">
            <div class="table-responsive">
                <table class="table table-sm table-striped fs--1 mb-0 overflow-hidden">
                    <thead class="bg-200 text-900">
                    <tr>
                        <th>
                            <div class="form-check fs-0 mb-0 d-flex align-items-center">
                                <input class="form-check-input" id="checkbox-bulk-customers-select" type="checkbox"
                                       data-bulk-select='{"body":"table-customers-body","actions":"table-customers-actions","replacedElement":"table-customers-replace-element"}'/>
                            </div>
                        </th>
                        <th class="sort pe-1 align-middle white-space-nowrap" data-sort="name">Name</th>
                        <th class="sort pe-1 align-middle white-space-nowrap" data-sort="email">Email</th>
                        <th class="sort pe-1 align-middle white-space-nowrap" data-sort="phone">Phone</th>
                        <th class="sort pe-1 align-middle white-space-nowrap ps-5" data-sort="address"
                            style="min-width: 200px;">Billing Address
                        </th>
                        <th class="sort pe-1 align-middle white-space-nowrap" data-sort="joined">Joined</th>
                        <th class="align-middle no-sort"></th>
                    </tr>
                    </thead>
                    <tbody class="list" id="table-customers-body">
                    {% for customer in customers %}
                        <tr class="btn-reveal-trigger">
                            <td class="align-middle py-2" style="width: 28px;">
                                <div class="form-check fs-0 mb-0 d-flex align-items-center">
                                    <input class="form-check-input" type="checkbox" id="customer-0"
                                           data-bulk-select-row="data-bulk-select-row"/>
                                </div>
                            </td>
                            <td class="name align-middle white-space-nowrap py-2"><a
                                    href="{% url 'ecommerce:customer_details' customer.id %}">
                                <div class="d-flex d-flex align-items-center">
                                    <div class="avatar avatar-xl me-2">
                                        {% if customer.customer_image %}
                                            <img src="{{ customer.get_absolute_url }}"
                                                 class="rounded-circle">
                                        {% else %}
                                            <div class="avatar-name rounded-circle d-flex align-items-center justify-content-center bg-secondary text-white"
                                                 style="width: 50px; height: 50px;">
                                                <span id="avatar-initials">M</span>
                                            </div>
                                        {% endif %}
                                    </div>

                                    <div class="flex-1">
                                        <h5 class="mb-0 fs--1">{{ customer.full_name }}</h5>
                                    </div>
                                </div>
                            </a></td>
                            <td class="email align-middle py-2"><a
                                    href="mailto:ricky@example.com">{{ customer.email }}</a>
                            </td>
                            <td class="phone align-middle white-space-nowrap py-2"><a
                                    href="tel:{{ customer.phone_number }}">{{ customer.phone_number }}</a></td>
                            <td class="address align-middle white-space-nowrap ps-5 py-2">{{ customer.address }}</td>
                            <td class="joined align-middle py-2">{{ customer.created_date }}</td>
                            <td class="align-middle white-space-nowrap py-2 text-end">
                                <div class="dropdown font-sans-serif position-static">
                                    <button class="btn btn-link text-600 btn-sm dropdown-toggle btn-reveal"
                                            type="button" id="customer-dropdown-0" data-bs-toggle="dropdown"
                                            aria-haspopup="true" aria-expanded="false">
                                        <span class="fas fa-ellipsis-h fs--1"></span>
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-end border py-0"
                                         aria-labelledby="customer-dropdown-0">
                                        <div class="bg-white py-2">
                                            <a class="dropdown-item"
                                               href="{% url 'ecommerce:edit_customer' customer.id %}">Edit</a>
                                            <form method="POST"
                                                  action="{% url 'ecommerce:delete_customer' customer.id %}"
                                                  onsubmit="return confirmDelete()">
                                                {% csrf_token %}
                                                <button type="submit" class="dropdown-item text-danger">Delete</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>

                                <script>
                                    function confirmDelete() {
                                        return confirm("Siz haqiqatdan ham ushbu foydalanuvchini o‘chirib tashlamoqchimisiz?");
                                    }
                                </script>

                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="card-footer d-flex align-items-center justify-content-center">
            <button class="btn btn-sm btn-falcon-default me-1" type="button" title="Previous"
                    data-list-pagination="prev"><span class="fas fa-chevron-left"></span></button>
            <ul class="pagination mb-0"></ul>
            <button class="btn btn-sm btn-falcon-default ms-1" type="button" title="Next" data-list-pagination="next">
                <span class="fas fa-chevron-right"></span></button>
        </div>
    </div>

{% endblock %}

ecommerce/templates/ecommerce/shopping-cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>